/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/legend.glb 
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LEGEND(props) {

  const { nodes, materials } = useGLTF('./models/legend.glb');

  const steer = useRef();

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube010.geometry} material={materials['STEER_Baked.001']} position={[-0.431, 0.002, -0.174]} rotation={[1.304, 1.57, 0]} scale={[0.049, 0.026, 0.049]} />
      <group position={[0.847, -0.418, -1.404]}>
        <group position={[-1.702, 0, 0]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel001_1.geometry} material={materials['wheel.0']} />
          <mesh geometry={nodes.wheel001_2.geometry} material={materials['wheel.1']} />
          <mesh geometry={nodes.wheel001_3.geometry} material={materials['chassis.2']} />
        </group>
        <group position={[0, 0, 2.811]}>
          <mesh geometry={nodes.wheel002_1.geometry} material={materials['wheel.0']} />
          <mesh geometry={nodes.wheel002_2.geometry} material={materials['wheel.1']} />
          <mesh geometry={nodes.wheel002_3.geometry} material={materials['chassis.2']} />
        </group>
        <group position={[-1.702, 0, 2.811]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel003_1.geometry} material={materials['wheel.0']} />
          <mesh geometry={nodes.wheel003_2.geometry} material={materials['wheel.1']} />
          <mesh geometry={nodes.wheel003_3.geometry} material={materials['chassis.2']} />
        </group>
        <mesh geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh geometry={nodes.wheel_3.geometry} material={materials['chassis.2']} />
      </group>
      <group position={[0, 0.162, -0.86]}>
        <mesh geometry={nodes.bonnet_ok_1.geometry} material={materials.primary} />
        <mesh geometry={nodes.bonnet_ok_2.geometry} material={materials['bonnet_ok.1']} />
      </group>
      <group position={[0, 0.568, 1.029]}>
        <mesh geometry={nodes.boot_ok_1.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.boot_ok_2.geometry} material={materials['bonnet_ok.1']} />
      </group>
      <group position={[0.862, -0.066, -2.189]}>
        <mesh geometry={nodes.bump_front_ok_1.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.bump_front_ok_2.geometry} material={materials['bonnet_ok.1']} />
        <mesh geometry={nodes.bump_front_ok_3.geometry} material={materials['right front light']} />
        <mesh geometry={nodes.bump_front_ok_4.geometry} material={materials['left front light']} />
        <mesh geometry={nodes.bump_front_ok_5.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.bump_front_ok_6.geometry} material={materials['bump_front_ok.5']} />
        <mesh geometry={nodes.bump_front_glass_ok.geometry} material={materials.glass} />
        <mesh geometry={nodes.bump_front_headglass_ok_1.geometry} material={materials['bump_front_headglass_ok.0']} />
        <mesh geometry={nodes.bump_front_headglass_ok_2.geometry} material={materials['bump_front_headglass_ok.1']} />
      </group>
      <group position={[-0.875, 0.142, 2.262]}>
        <mesh geometry={nodes.bump_rear_ok_1.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.bump_rear_ok_2.geometry} material={materials['bonnet_ok.1']} />
        <mesh geometry={nodes.bump_rear_ok_3.geometry} material={materials['bump_front_ok.5']} />
        <mesh geometry={nodes.bump_rear_ok_4.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_1.geometry} material={materials['bump_front_headglass_ok.0']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_2.geometry} material={materials['bump_rear_lightsglass_ok.1']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_3.geometry} material={materials['bump_front_headglass_ok.1']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_4.geometry} material={materials['bump_rear_lightsglass_ok.3']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_5.geometry} material={materials['bump_rear_lightsglass_ok.4']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_6.geometry} material={materials['bump_rear_lightsglass_ok.5']} />
        <mesh geometry={nodes.bump_rear_lightsglass_ok_7.geometry} material={materials['bump_rear_lightsglass_ok.6']} />
      </group>
      <group position={[0, 0.008, 0.046]}>
        <mesh geometry={nodes.chassis_1.geometry} material={materials.primary} />
        <mesh geometry={nodes.chassis_2.geometry} material={materials['bonnet_ok.1']} />
        <mesh geometry={nodes.chassis_3.geometry} material={materials['chassis.2']} />
        <mesh geometry={nodes.chassis_4.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.chassis_5.geometry} material={materials['chassis.4']} />
        <mesh geometry={nodes.chassis_6.geometry} material={materials['chassis.5']} />
        <mesh geometry={nodes.chassis_7.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.chassis_8.geometry} material={materials['left front light']} />
        <mesh geometry={nodes.chassis_9.geometry} material={materials['right front light']} />
        <mesh geometry={nodes.delorean_dials.geometry} material={materials.interior} position={[0, -0.008, -0.046]} />
        <mesh geometry={nodes.delorean_dials001.geometry} material={materials.interior} position={[-0.386, 0.061, -0.477]} />
        <mesh geometry={nodes.delorean_dials002.geometry} material={materials.interior} position={[-0.319, 0.091, -0.474]} />
        <mesh geometry={nodes.delorean_dials003.geometry} material={materials.interior} position={[-0.319, 0.032, -0.474]} />
        <mesh geometry={nodes.delorean_dials004.geometry} material={materials.interior} position={[-0.49, 0.061, -0.477]} />
        <mesh geometry={nodes.delorean_dials005.geometry} material={materials.interior} position={[-0.553, 0.091, -0.474]} />
        <mesh geometry={nodes.delorean_dials006.geometry} material={materials.interior} position={[-0.553, 0.031, -0.474]} />
        <group position={[0, -0.008, -0.046]}>
          <mesh geometry={nodes.delorean_interior_1.geometry} material={materials.interior} />
          <mesh geometry={nodes.delorean_interior_2.geometry} material={materials['bump_front_ok.4']} />
        </group>
        <mesh geometry={nodes.delorean_interior_badges.geometry} material={materials['delorean_seats.1']} position={[0, -0.008, -0.046]} />
        <group position={[0, -0.008, -0.046]}>
          <mesh geometry={nodes.delorean_seats_1.geometry} material={materials.interior} />
          <mesh geometry={nodes.delorean_seats_2.geometry} material={materials['delorean_seats.1']} />
        </group>
        <group position={[0, -0.008, -0.046]}>
          <mesh geometry={nodes.delorean_interior001.geometry} material={materials.interior} />
          <mesh geometry={nodes.delorean_interior001_1.geometry} material={materials['bump_front_ok.4']} />
        </group>
      </group>
      <mesh geometry={nodes.delorean_glass.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.door_lf.geometry} material={materials['chassis.5']} position={[-0.159, 0.517, -0.019]} rotation={[1.559, 0, 0]}>
        <mesh geometry={nodes.mirrorL.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.door_lf_ok_1.geometry} material={materials.primary} />
        <mesh geometry={nodes.door_lf_ok_2.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.door_lf_ok_3.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.door_lf_ok_4.geometry} material={materials['bonnet_ok.1']} />
        <mesh geometry={nodes.door_lf_ok_5.geometry} material={materials.interior} />
        <mesh geometry={nodes.door_lf_glass_ok.geometry} material={materials['glass.001']} />
      </mesh>
      <mesh geometry={nodes.door_rf.geometry} material={materials['chassis.5']} position={[0.16, 0.517, -0.019]} rotation={[1.559, 0, 0]}>
        <mesh geometry={nodes.mirrorR.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.door_rf_ok_1.geometry} material={materials.primary} />
        <mesh geometry={nodes.door_rf_ok_2.geometry} material={materials['boot_ok.0']} />
        <mesh geometry={nodes.door_rf_ok_3.geometry} material={materials['bump_front_ok.4']} />
        <mesh geometry={nodes.door_rf_ok_4.geometry} material={materials['bonnet_ok.1']} />
        <mesh geometry={nodes.door_rf_ok_5.geometry} material={materials.interior} />
        <mesh geometry={nodes.door_rf_glass_ok.geometry} material={materials['glass.001']} />
      </mesh>
      <mesh geometry={nodes.windscreen_ok.geometry} material={materials['glass.001']} position={[0, 0.361, -0.499]} />
    </group>
  )
}

useGLTF.preload('./models/legend.glb')
