/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/signs.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Signs(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/signs.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text023" geometry={nodes.Text023.geometry} material={materials['Hologram.024']} position={[2.806, 10.187, -70.249]} rotation={[Math.PI / 2, 0, 0.932]} scale={4.31} />
        <mesh name="Text033" geometry={nodes.Text033.geometry} material={materials['Hologram.009']} position={[7.313, 3.856, 29.018]} rotation={[Math.PI / 2, 0, 1.329]} scale={0.652} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Hologram.011']} position={[7.012, 12.364, 5.453]} rotation={[Math.PI / 2, -0.201, Math.PI / 2]} scale={1.418} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Hologram.012']} position={[-4.03, 10.253, -10.965]} rotation={[0, -0.71, 0]} scale={[-1, -0.124, -44.3]} />
        <mesh name="Text040" geometry={nodes.Text040.geometry} material={materials['Hologram.013']} position={[-4.021, 11.893, -10.678]} rotation={[Math.PI / 2, 0, 0]} scale={0.753} />
        <mesh name="css-logo" geometry={nodes['css-logo'].geometry} material={materials['Hologram.014']} position={[5.672, 6.861, -5.23]} rotation={[Math.PI / 2, 0, 1.082]} scale={2.55} />
        <mesh name="nodejs" geometry={nodes.nodejs.geometry} material={materials['Hologram.015']} position={[3.992, 9.048, -17.897]} rotation={[Math.PI / 2, 0, 0.81]} scale={2.032} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials['Hologram.016']} position={[4.379, 11.967, -14.889]} rotation={[0.001, 0, Math.PI / 2]} scale={1.161} />
        <mesh name="React_logo_wordmark" geometry={nodes.React_logo_wordmark.geometry} material={materials['Hologram.017']} position={[4.515, 11.987, -13.118]} rotation={[Math.PI / 2, 0, 1.504]} scale={1.925} />
        <mesh name="tailwind" geometry={nodes.tailwind.geometry} material={materials['Hologram.018']} position={[4.038, 17.184, -12.627]} rotation={[Math.PI / 2, 0, 1.505]} scale={[5.218, 3.782, 3.782]} />
        <mesh name="Text043" geometry={nodes.Text043.geometry} material={materials['Hologram.019']} position={[-4.314, 5.253, -21.295]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.247, 1.112, 2.159]} />
        <mesh name="Text045" geometry={nodes.Text045.geometry} material={materials['Hologram.020']} position={[-4.316, 13.246, -26.655]} rotation={[1.615, 0.194, 0.071]} scale={1.099} />
        <mesh name="Text024" geometry={nodes.Text024.geometry} material={materials['Hologram.021']} position={[5.26, 0.92, -36.467]} rotation={[1.332, 0, Math.PI / 2]} scale={1.109} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/signs.glb')
